# from email.mime import audio
# from platform import architecture
# from termios import CQUIT
# from tkinter import W
from socket import socket
import socketio

print("THISNOIANSDOIANSDOINASD")

aio = socketio.AsyncClient()
bio = socketio.AsyncClient()
cio = socketio.AsyncClient()
dio = socketio.AsyncClient()
eio = socketio.AsyncClient()
fio = socketio.AsyncClient()
gio = socketio.AsyncClient()
hio = socketio.AsyncClient()
iio = socketio.AsyncClient()
jio = socketio.AsyncClient()
kio = socketio.AsyncClient()
lio = socketio.AsyncClient()
mio = socketio.AsyncClient()
nio = socketio.AsyncClient()
oio = socketio.AsyncClient()
pio = socketio.AsyncClient()
qio = socketio.AsyncClient()
rio = socketio.AsyncClient()
sio = socketio.AsyncClient()
tsio = socketio.AsyncClient()
usio = socketio.AsyncClient()
vsio = socketio.AsyncClient()
wsio = socketio.AsyncClient()
xio = socketio.AsyncClient()
yio = socketio.AsyncClient()
zio = socketio.AsyncClient()
aaio = socketio.AsyncClient()
abio = socketio.AsyncClient()
acio = socketio.AsyncClient()
adio = socketio.AsyncClient()
aeio = socketio.AsyncClient()
afio = socketio.AsyncClient()
agio = socketio.AsyncClient()
ahio = socketio.AsyncClient()
aiio = socketio.AsyncClient()
ajio = socketio.AsyncClient()
akio = socketio.AsyncClient()
alio = socketio.AsyncClient()
amio = socketio.AsyncClient()
anio = socketio.AsyncClient()
aoio = socketio.AsyncClient()
apio = socketio.AsyncClient()
aqio = socketio.AsyncClient()
ario = socketio.AsyncClient()
asio = socketio.AsyncClient()
atio = socketio.AsyncClient()
auio = socketio.AsyncClient()
avio = socketio.AsyncClient()
awio = socketio.AsyncClient()
axio = socketio.AsyncClient()
ayio = socketio.AsyncClient()
azio = socketio.AsyncClient()
baio = socketio.AsyncClient()
bbio = socketio.AsyncClient()
bcio = socketio.AsyncClient()
bdio = socketio.AsyncClient()
beio = socketio.AsyncClient()
bfio = socketio.AsyncClient()
bgio = socketio.AsyncClient()
bhio = socketio.AsyncClient()
biio = socketio.AsyncClient()
bjio = socketio.AsyncClient()
bkio = socketio.AsyncClient()
blio = socketio.AsyncClient()
bmio = socketio.AsyncClient()
bnio = socketio.AsyncClient()
boio = socketio.AsyncClient()
bpio = socketio.AsyncClient()
bqio = socketio.AsyncClient()
brio = socketio.AsyncClient()
bsio = socketio.AsyncClient()
btio = socketio.AsyncClient()
buio = socketio.AsyncClient()
bvio = socketio.AsyncClient()
bwio = socketio.AsyncClient()
bxio = socketio.AsyncClient()
byio = socketio.AsyncClient()
bzio = socketio.AsyncClient()
caio = socketio.AsyncClient()
cbio = socketio.AsyncClient()
ccio = socketio.AsyncClient()
cdio = socketio.AsyncClient()
ceio = socketio.AsyncClient()
cfio = socketio.AsyncClient()
cgio = socketio.AsyncClient()
chio = socketio.AsyncClient()
ciio = socketio.AsyncClient()
cjio = socketio.AsyncClient()
ckio = socketio.AsyncClient()
clio = socketio.AsyncClient()
cmio = socketio.AsyncClient()
cnio = socketio.AsyncClient()
coio = socketio.AsyncClient()
cpio = socketio.AsyncClient()
cqio = socketio.AsyncClient()
crio = socketio.AsyncClient()
csio = socketio.AsyncClient()
ctio = socketio.AsyncClient()
cuio = socketio.AsyncClient()
cvio = socketio.AsyncClient()
cwio = socketio.AsyncClient()
cxio = socketio.AsyncClient()
cyio = socketio.AsyncClient()
czio = socketio.AsyncClient()
daio = socketio.AsyncClient()
dbio = socketio.AsyncClient()
dcio = socketio.AsyncClient()
ddio = socketio.AsyncClient()
deio = socketio.AsyncClient()
dfio = socketio.AsyncClient()
dgio = socketio.AsyncClient()
dhio = socketio.AsyncClient()
diio = socketio.AsyncClient()
djio = socketio.AsyncClient()
dkio = socketio.AsyncClient()
dlio = socketio.AsyncClient()
dmio = socketio.AsyncClient()
dnio = socketio.AsyncClient()
doio = socketio.AsyncClient()
dpio = socketio.AsyncClient()
dqio = socketio.AsyncClient()
drio = socketio.AsyncClient()
dsio = socketio.AsyncClient()
dtio = socketio.AsyncClient()
duio = socketio.AsyncClient()
dvio = socketio.AsyncClient()
dwio = socketio.AsyncClient()
dxio = socketio.AsyncClient()
dyio = socketio.AsyncClient()
dzio = socketio.AsyncClient()
eaio = socketio.AsyncClient()
ebio = socketio.AsyncClient()
ecio = socketio.AsyncClient()
edio = socketio.AsyncClient()
eeio = socketio.AsyncClient()
efio = socketio.AsyncClient()
egio = socketio.AsyncClient()
ehio = socketio.AsyncClient()
eiio = socketio.AsyncClient()
ejio = socketio.AsyncClient()
ekio = socketio.AsyncClient()
elio = socketio.AsyncClient()
emio = socketio.AsyncClient()
enio = socketio.AsyncClient()
eoio = socketio.AsyncClient()
epio = socketio.AsyncClient()
eqio = socketio.AsyncClient()
erio = socketio.AsyncClient()
esio = socketio.AsyncClient()
etio = socketio.AsyncClient()
euio = socketio.AsyncClient()
evio = socketio.AsyncClient()
ewio = socketio.AsyncClient()
exio = socketio.AsyncClient()
eyio = socketio.AsyncClient()
ezio = socketio.AsyncClient()
#### create a disconnnect function here. 

#### another approach is decorate the on fucntion with 2 on, so you can connect using a new asyncclient. Essentially each "channel" will get 2 sockets for it assigned one at a time. like qsio and sio will be assiogn for 1st socket. 
# @sio.event
# def connect():
#     print("I'm connected!")

# @sio.event
# def connect_error(data):
#     print("The connection failed!")

# @sio.event
# def disconnect():
#     print("I'm disconnected!")

# sio.connect('http://localhost:5005/socket.io')
# print("SIS id is ",sio.sid)